### ISSUE TITLE
channel not subscribe

### ISSUE THREAD

**Issue by asifyounas708** [kerimamansaryyev/dart_pusher_channels#53]
Attempted to ChannelTriggerEvent "private-all-chat.1" when Channel private-all-chat.1 was not subscribed. Ignoring the attempt silently.

**Comment by asifyounas708** [comment]
Current lifecycle state: PusherChannelsClientLifeCycleState.connectionError
flutter: Connection error: SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = wechat.cslancer.com, port = 50941 trace #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26)
socket_patch.dart:1920
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
socket_patch.dart:27
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22)
socket_patch.dart:2144
#4      Socket.startConnect (dart:io/socket.dart:825:21)
socket.dart:825
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20)
http_impl.dart:2491
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12)
http_impl.dart:2930
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12)
http_impl.dart:2935
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12)
http_impl.dart:2790
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2627:7)
http_impl.dart:2627
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
websocket_impl.dart:1021
#11     WebSocket.connect (dart:_http/websocket.dart:320:22)
websocket.dart:320
#12     new IOWebSoc<…>
flutter: Current lifecycle state: PusherChannelsClientLifeCycleState.reconnecting

**Comment by kerimamansaryyev** [comment]
> Attempted to ChannelTriggerEvent "private-all-chat.1" when Channel private-all-chat.1 was not subscribed. Ignoring the attempt silently.

This is reasonable since the client didn't subscribe to the channel. I guess your client couldn't connect, hence, it can't subscribe to the channel.

**Comment by kerimamansaryyev** [comment]
> Current lifecycle state: PusherChannelsClientLifeCycleState.connectionError flutter: Connection error: SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = wechat.cslancer.com, port = 50941 trace #0 _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35) #1 _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26) socket_patch.dart:1920 #2 RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23) socket_patch.dart:27 #3 Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22) socket_patch.dart:2144 #4 Socket.startConnect (dart:io/socket.dart:825:21) socket.dart:825 #5 _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20) http_impl.dart:2491 #6 _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12) http_impl.dart:2930 #7 _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12) http_impl.dart:2935 #8 _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12) http_impl.dart:2790 #9 _HttpClient.openUrl (dart:_http/http_impl.dart:2627:7) http_impl.dart:2627 #10 _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42) websocket_impl.dart:1021 #11 WebSocket.connect (dart:_http/websocket.dart:320:22) websocket.dart:320 #12 new IOWebSoc<…> flutter: Current lifecycle state: PusherChannelsClientLifeCycleState.reconnecting

Here, most probably, the error was with the server. You can look up similar issues among the closed issues, you will find a lot. For now, I can only guess since you didn't provide enough information. Try describing the steps to reproduce the problem, sharing some sample code with the issue present, etc

**Comment by asifyounas708** [comment]
Thanks.
